#!/bin/env bash
ME=$(basename $0)
MYDIR="$(cd "$(dirname "$0")" > /dev/null 2>&1 && pwd -P)"
ROOT="${MYDIR}/../"
cd "${ROOT}"

FBDS="$(hlq).DIO.FB.RDDIR"
drm -f "${FBDS}"
dtouch -rfb -l80 -B80 "${FBDS}"
decho  "Hello There
Joe" "${FBDS}(MEM@)"

VBDS="$(hlq).DIO.VB.RDDIR"
drm -f "${VBDS}"
dtouch -rfb -l80 -B80 "${VBDS}"
decho  "Hello There
Jeff" "${VBDS}(MEM@)"

echo "Read ${FBDS}(MEM@)"
bin/basicread "${FBDS}" "MEM@"

echo "Read ${VBDS}(MEM@)"
bin/basicread "${VBDS}" "MEM@"

echo "Done"

exit $?
