#!/bin/sh

ME=$(basename $0)
MYDIR="$(cd "$(dirname "$0")" > /dev/null 2>&1 && pwd -P)"
ROOT="${MYDIR}/../"
cd "${ROOT}"

#
# Test will copy files from a couple directories
# to a mapped set of datasets.
# Need to allocate datasets first
#

hlq=$(hlq)
mlq="DIO.F2M"
drm -f "${hlq}.${mlq}.*"

dtouch "${hlq}.${mlq}.c"
dtouch "${hlq}.${mlq}.h"
dtouch "${hlq}.${mlq}.s"
dtouch "${hlq}.${mlq}.dbg"
dtouch "${hlq}.${mlq}.o"
dtouch -l 137 -r vba "${hlq}.${mlq}.lst"

time bin/f2m src "${hlq}.${mlq}" '*.*'
time bin/f2m include "${hlq}.${mlq}" '*.*'

#
# run again with all members already existing
#
time bin/f2m src "${hlq}.${mlq}" '*.*'
time bin/f2m include "${hlq}.${mlq}" '*.*'
