#!/bin/sh
#
# Basic script to compile / link code to test dataset listing services
#

# Use set -e to force failure if something doesn't build
set -e

. ./setenv

gmake -C src
gmake -C test
gmake -C sample
