#!/bin/sh

set -e

xmplib=$(echo "$(hlq).ASMXMP.LOAD")
xmpadata=$(echo "$(hlq).ASMXMP.SYSADATA")
xmplangx=$(echo "$(hlq).ASMXMP.ASMLANGX")
pgm='rdmccsid'

drm -f ${xmplib}
dtouch -tPDS -ru ${xmplib}

drm -f ${xmplangx}
dtouch -tSEQ -rvb -l1562 ${xmplangx}
drm -f ${xmpadata}
dtouch -tSEQ -rvb -l1562 ${xmpadata}

as --LIST,SUPRWARN\(425,434\) "--gadata=//'${xmpadata}'" ${pgm}.s >${pgm}.lst

mvscmd --pgm=ASMLANGX --args=${pgm} --sysadata="${xmpadata}" --asmlangx="${xmplangx},old" --sysprint=*

ld -o"//'${xmplib}(${pgm})'" ${pgm}.o

