#!/bin/sh

set -e

xmplib=$(echo "$(hlq).ASMXMP.LOAD")
drm -f ${xmplib}
dtouch -tPDS -ru ${xmplib}

as --LIST,SUPRWARN\(425,434\),TEST rdmem.s >rdmem.lst
ld -bTEST -V -o"//'${xmplib}(RDMEM)'" rdmem.o

