#!/bin/sh

set -e
set -x

xmplib=$(echo "$(hlq).ASMXMP.LOAD")
xmpadata=$(echo "$(hlq).ASMXMP.SYSADATA")
xmplangx=$(echo "$(hlq).ASMXMP.ASMLANGX")
drm -f ${xmplib}
dtouch -tPDS -ru ${xmplib}

drm -f ${xmplangx}
dtouch -tSEQ -rvb -l1562 ${xmplangx}
drm -f ${xmpadata}
dtouch -tSEQ -rvb -l1562 ${xmpadata}

as --LIST,SUPRWARN\(425,434\) "--gadata=//'${xmpadata}'" rdmem.s >rdmem.lst

mvscmd --pgm=ASMLANGX --args='RDMEM' --sysadata="${xmpadata}" --asmlangx="${xmplangx},old" --sysprint=*

ld -bTEST -V -o"//'${xmplib}(RDMEM)'" rdmem.o

