#!/bin/sh

set -e

wrtlib=$(echo "$(hlq).ASMXMP.DATA")
drm -f "${wrtlib}"
dtouch -B6160 -tPDS "${wrtlib}"

xmplib=$(echo "$(hlq).ASMXMP.LOAD")

mvscmd --steplib=$xmplib --pds="${wrtlib}" --pgm=CRTMEMB
