#!/bin/env bash
ME=$(basename $0)
MYDIR="$(cd "$(dirname "$0")" > /dev/null 2>&1 && pwd -P)"
cd "${MYDIR}"

set -e
FBDS="$(hlq).DIO.FB.BASICCRT"
drm -f "${FBDS}"
dtouch -rfb -l80 "${FBDS}"

bin/basiccreate "${FBDS}" "JOE"
exit $?
